services:
  server:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_URL=${DB_POSTGRES_URL}
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "potatoes" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api-gateway:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  db-data: